name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the MASTER Docker image
      run: docker build . --file MASTER.Dockerfile --tag pihole-keepalived:master
    - name: Build the BACKUP Docker image
      run: docker build . --file BACKUP.Dockerfile --tag pihole-keepalived:backup
